name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /Users/nathanblatter/Desktop/secreth
          git pull origin main
          docker compose down
          docker compose build --no-cache
          docker compose up -d
